trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  patch: $[counter('versioncounter', 89)]
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

name: 1.0.$(patch)

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      command: "restore"

  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      maximumCpuCount: true
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"

  - task: VSTest@2
    inputs:
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: |
        README.md
        build/**
        **/*.vsix
        **/*.nupkg
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "drop"
      targetPath: "$(Build.ArtifactStagingDirectory)"
